title: Renjin.org
description: Homepage of Renjin, the R programming language on the JVM
url: http://www.renjin.org

renjin-current: RELEASE

markdown: pandoc
pandoc:
    extensions:
        - smart

exclude: [README.md]

permalink: /blog/:year-:month-:day-:title.html
