title: Renjin.org
description: Blog about Renjin, the R programming language on the JVM
url: http://www.renjin.org

renjin-current: 0.7.0-RC6

markdown: pandoc
pandoc:
    extensions:
        - smart

exclude: [README.md]

permalink: /blog/:year-:month-:day-:title.html
