title: Renjin.org
description: Blog about Renjin, the R programming language on the JVM
url: http://www.renjin.org

markdown: pandoc
pandoc:
    extensions:
        - smart

exclude: [README.md]

permalink: /blog/:year-:month-:day-:title.html
