runtime: python312
service: default

handlers:
- url: /
  static_files: output/index.html
  upload: output/index.html
  secure: always

- url: /blog/
  static_files: output/blog/index.html
  upload: output/blog/index.html
  secure: always

- url: /blog
  static_files: output/blog/index.html
  upload: output/blog/index.html
  secure: always

- url: /(.*)
  static_files: output/\1
  upload: output/(.*)
  secure: always
