runtime: python27
api_version: 1
threadsafe: true
service: static

handlers:
- url: /
  static_files: output/index.html
  upload: output/index.html

- url: /(.*)
  static_files: output/\1
  upload: output/(.*)
